### ISSUE TITLE
per participant pages in the gui

### ISSUE THREAD

**Issue by momedo** [textbrowser/smoke#1]
please create per participant one dedicated chat page 
(also regard several participants as a group in one page / timeline)

**Comment by textbrowser** [comment]
Working on this now. Next release!

**Comment by textbrowser** [comment]
OK, reviewed the work required. Monumental. The Chat activity would be duplicated. One main Chat activity and a member-only Chat activity. The main Chat activity must retain all of its capabilities while also supporting some new capabilities. The member-only activity would require duplication of many of the main Chat activity functions. Either with fragments or activities, the work required would be to replace Chat as an activity and partition its functionality into fragments as well as an activity. There are also changes to the kernel, the state container, Settings (broadcasts), and unknowns.

I'm not prepared to do all of this.

**Comment by textbrowser** [comment]
Available with the 2018.08.19 release.
