### ISSUE TITLE
Why are Tags being deleted?

### ISSUE THREAD

**Issue by licaon-kter** [textbrowser/smoke#10]
Eg. https://f-droid.org/wiki/index.php?title=org.purple.smoke/lastbuild_20210225&oldid=288052

Also, all the F-Droid versions are unbuildable now as Tag references are...gone.

**Comment by textbrowser** [comment]
Release tags? I maintain a single tag, usually the most recent, for all of my projects. Apologies. I'll keep all releases from now on.

**Comment by textbrowser** [comment]
Version 2021.07.07 is ready. Thanks.
