### ISSUE TITLE
how to run smoke chat with smoke stack ?

### ISSUE THREAD

**Issue by huutien98** [textbrowser/smoke#16]
hello every one im a student and I am working on a graduation project related to smoke , but i Can't use the functions on the smoke app , please show me how to implement and use the smoke chat feature, this is very important to my life . I don't speak English well I hope you understand .  i come from vietnam ,Thanks a lot

**Comment by huutien98** [comment]
Thanks for answering
i tried but it seems i don't know how to implement sport on can you show me the steps to implement it 
Does Spot-On have to run on linux OS?

**Comment by textbrowser** [comment]
Spot-On runs just about anywhere. What operating systems do you have available?

**Comment by huutien98** [comment]
i use windows. I see the open source code of sport on is C, C++ so which ide can run it? , i tried with android studio and vs code but failed

**Comment by huutien98** [comment]
i tried with these command lines but failed , where am i going wrong ?
![image](https://user-images.githubusercontent.com/41584186/139706192-ef214c5f-9b0e-4c27-ac98-ac021eaf5114.png)

**Comment by textbrowser** [comment]
Notice the file extension on the README file. That file is for Debian. :)

https://github.com/textbrowser/spot-on/releases/tag/2021.10.20

Download Spot-On.zip, unzip it, and launch Spot-On.exe.

**Comment by textbrowser** [comment]
I'll post a video tutorial for Windows soon. I'm occupied at the moment so you'll have to discover the program on your own. Perhaps later tonight or tomorrow; for the video.

**Comment by huutien98** [comment]
thank you very much , this is a project for me to graduate , it is very important to me . If I have questions can I ask more?

**Comment by textbrowser** [comment]
Sure, but I may not respond right away.

**Comment by textbrowser** [comment]
You will need at least two Android devices to test Smoke. You can use Android Studio as it allows you to create virtual devices.

**Comment by textbrowser** [comment]
Here's the video. When creating a listener, assign it an IP address which is accessible by your other devices.

https://user-images.githubusercontent.com/10701156/139751333-b5727b9e-d2f8-442a-a0e6-12e82eddf868.mov

**Comment by textbrowser** [comment]
Of course I forgot to mention that you can also use SmokeStack. You will need an additional Android device.

**Comment by huutien98** [comment]
Thanks for the help, I'll try it out

**Comment by huutien98** [comment]
![image](https://user-images.githubusercontent.com/41584186/139881340-03611584-a0a3-4499-a8fa-595480b562c3.png)
![image](https://user-images.githubusercontent.com/41584186/139881866-71ceaadd-50b3-4bdc-89a9-520a03f424ae.png)

I've tried everything I can, but it seems smoke still can't connect to its server

**Comment by textbrowser** [comment]
In Smoke, the IP addresses are incorrect. Suppose you create the listener 192.168.178.15:4710 in Spot-On and suppose that listener is accessible by a device beyond the machine. Then, in Smoke, you create a neighbor having the destination 192.168.178.15:4710. :)

**Comment by textbrowser** [comment]
Here's my device connected to SO-Lite.
![device-2021-11-02-120138](https://user-images.githubusercontent.com/10701156/139892409-1f6e6d04-1255-4a31-a96e-885f1e031e26.png)

**Comment by huutien98** [comment]
yeah i did it . Thanks a lot
![151521123_852517818873312_4779965190660297411_n](https://user-images.githubusercontent.com/41584186/139896455-8238b8f3-e60c-4298-bdeb-9c36147b9486.jpg)

**Comment by textbrowser** [comment]
Easy. :) Now you need another device. Then, you can either use SipHash IDs or aliases and exchange credentials. But that's for another time.

**Comment by textbrowser** [comment]
Closing. Please open a new discussion / ticket if you need to. Thanks!
