### ISSUE TITLE
Connecting Smoke to SmokeStack.

### ISSUE THREAD

**Issue by Mehsud111** [textbrowser/smoke#24]
Hello smoke developers. I am glade to see such a great idea of communication. I had tried for 2 days and nights to configure the smokestack and smoke app but failed. I go through the guide but it is very complicated. I also discussed in different xmpp rooms to get help but no one know. 
I have successfully configured the smokestack with my device (android ip address with port 4710 as listener) and smoke app with the same ip and port as neighbor on same device. Now in documentation of GB it is said that other person/friend can directly connect to me. I cannot figure that.
Is it important that my friend should also install and configure both smoke and smokestack as I did? or he can connect to my smokestack ip and port to communicate with me.

lastly I will be of huge guidance if you please post a configuration video of this.
Looking forward for your kind feedback, please

**Comment by textbrowser** [comment]
There is one developer. Not developers.

**Comment by Mehsud111** [comment]
My apology!

**Comment by textbrowser** [comment]
How? The information is very clear.

Posted a new video for defining a listener in SmokeStack.

**Comment by textbrowser** [comment]
https://github.com/textbrowser/smokestack

**Comment by textbrowser** [comment]
And a new video for a connected Smoke client.

https://github.com/textbrowser/smokestack

**Comment by textbrowser** [comment]
Indeed. I manually set it. SmokeStack will also detect a DHCP address.

**Comment by Mehsud111** [comment]
I am able to config the listener. Now how can I connect to it in smoke aap.

**Comment by textbrowser** [comment]
Smoke is a client. It cannot accept clients. It doesn't have listeners.

**Comment by textbrowser** [comment]
Smoke connects to SmokeStack.

**Comment by textbrowser** [comment]
Now I need to create a separate video for Smoke. It's all very simple.

**Comment by textbrowser** [comment]
Not the video-creation part. The Smoke process. It appears complex because everything you've seen hides everything from you.

**Comment by Mehsud111** [comment]
Yes please. This video will help.

**Comment by Mehsud111** [comment]
I have configured the smokestack listener. What to do next in smoke app

**Comment by textbrowser** [comment]
https://github.com/textbrowser/smoke

Added video.

**Comment by Mehsud111** [comment]
Done. Now what should I do further

**Comment by Mehsud111** [comment]
I mean do I have to create participants

**Comment by textbrowser** [comment]
That's the connection information.

**Comment by textbrowser** [comment]
You should explore and read the documentation. If you cannot establish a dialogue between yourself and your friends, Smoke may not be right for you. :)

**Comment by Mehsud111** [comment]
I would only bother you for a while. I spent 2 whole days. kindly assist a bit more so I can establish communication wit a friend, PLEASE!

**Comment by Mehsud111** [comment]
I am very glad for your help. ALL I want the final step kindly

**Comment by textbrowser** [comment]
I have other things to do. Perhaps later. You need to experiment and read the documentation.

**Comment by Mehsud111** [comment]
my friend has to install both apps and do the same configurations as I did?

**Comment by textbrowser** [comment]
No.

There is a public service IP noted on the README.md file. You can define a neighbor in Smoke without SmokeStack. SmokeStack has many other purposes.

**Comment by textbrowser** [comment]
If you're not going to explore Smoke, you should not use it.

**Comment by Mehsud111** [comment]
All right. but I am not able to connect to that public server

**Comment by Mehsud111** [comment]
ok. I have connected to that server ID on both of my devices. made participants. when I tap chat. thee is no send icon not call icon work

**Comment by textbrowser** [comment]
Closing as I'm not providing customer support. Best to read the documentation and experiment.
