### ISSUE TITLE
Needs more guidance for newcomers.

### ISSUE THREAD

**Issue by y0umu** [textbrowser/smoke#36]
Hi developer. I've come across your application on a random search on F-droid. I am not a tech-savvy person. Having read the repo's [README](https://github.com/textbrowser/smoke), the [website](https://textbrowser.github.io/smoke/), the [documention](https://github.com/textbrowser/smoke/blob/master/Documentation/Smoke.pdf) and issue #34, I learned a lot new technical terms. But I still have no idea of the whole picture. 

To be more precise, what do I need to do to make two peers send and receive text from each other? Is there a quick start? (so that people like me do not have to dive into the source code and the documention immediately, maybe like what wireguard [provides](https://www.wireguard.com/quickstart/))

**Comment by textbrowser** [comment]
There are https://github.com/textbrowser/smoke/discussions.

**Comment by textbrowser** [comment]
https://github.com/textbrowser/smoke/discussions/37
