### ISSUE TITLE
Delete Button for an Empty Firelist Channel

### ISSUE THREAD

**Issue by alexlenn** [textbrowser/smoke#48]
The delete button in an empty Fire-Channel List Tab causes the app to close/crash.
"Are you sure to delete the Fire Channel ("Empty")?"  yes. -> crash.

**Comment by textbrowser** [comment]
We resolve it soon!

**Comment by textbrowser** [comment]
Downloading Android Studio.

**Comment by textbrowser** [comment]
Android sucks.

**Comment by textbrowser** [comment]
![android-sucks](https://github.com/textbrowser/smoke/assets/10701156/44d325cb-7eea-421c-922b-da2bd8ad65ae)

**Comment by textbrowser** [comment]
Ten minutes in this state. If I visit the URL in the fancy Dooble, Dooble immediately proceeds as an uneventful download. Android is garbage.

**Comment by textbrowser** [comment]
This is the primary reason I do not fancy the tarnished development of so-called intelligent devices. Garbage in, garbage out. They are awful. Google is garbage.

**Comment by textbrowser** [comment]
A trillion dollar company cannot inform you that something it wrong. What is wrong? Do you mind waiting while we download a file? I do not know. If I cancel, I cannot do anything because I will later require these components that you refuse to download. And people idolize Google and Apple for their instructive, Godly, beautiful design. Garbage companies.

**Comment by textbrowser** [comment]
We would love to help but we cannot download. Heeee heee Google is garbage.

**Comment by textbrowser** [comment]
Meanwhile my Dooble download completed. A smart tool would inform me that the file is being downloaded into such-and-such a directory and I could correctly assist it with a proper download.

**Comment by textbrowser** [comment]
Still starting...

**Comment by textbrowser** [comment]
A wee bit of progress according to the progress bar but the text states that it is starting. So it starting but also progressing. Hee hee Android sucks is garbage.

**Comment by textbrowser** [comment]
40 minutes to prepare Studio.

**Comment by textbrowser** [comment]
I archive soon! Hee hee.
