### ISSUE TITLE
Unable To Register for New Account

### ISSUE THREAD

**Issue by KKenui** [textbrowser/smoke#5]
I downloaded the smoke app via Google play store. I am unable to register for a new account via email or the Facebook links. 

I was on Android 10 but just updated to Android 11 beta. Still not able to register to use. I checked website and nothing there. Sent a few emails but haven't heard anything back.

**Comment by textbrowser** [comment]
Register through Smoke? Smoke doesn't require registration. It requires participants and a common server.

You've installed an application which is not related to Smoke.

What's the Play Store link?

**Comment by textbrowser** [comment]
See https://textbrowser.github.io/smoke/. Also https://github.com/textbrowser/smoke/blob/master/Documentation/Smoke.pdf.

**Comment by textbrowser** [comment]
Closing!

**Comment by KKenui** [comment]
https://play.google.com/store/apps/details?id=com.hl.salals

http://www.smokemessaging.com/

ADDITIONAL INFORMATION
Updated
July 24, 2019
Size
14M
Installs
100+
Current Version
1.1
Requires Android
4.2 and up
Content Rating
Teen
Learn More <https://support.google.com/googleplay?p=appgame_ratings>
Interactive Elements
Users Interact
Permissions
View details
Report
Flag as inappropriate
<https://support.google.com/googleplay/?p=report_content>
Offered By
SMOKE Messaging
Developer
Visit website <http://www.smokemessaging.com/>
wade@smokemessaging.com
Privacy Policy <http://smokemessaging.com/>

**Comment by textbrowser** [comment]
That's a totally unrelated application from the official Smoke. :)

**Comment by textbrowser** [comment]
This Smoke is not in the Play Store.
