### ISSUE TITLE
Add a navigation drawer (rewrite)

### ISSUE THREAD

**Issue by lump-on** [textbrowser/smoke#7]
Hello,
checked your app Smoke today, nice crypto and messenger tool!

Please add a navigation drawer to your app to improve the ui experience:
https://developer.android.com/guide/navigation/navigation-ui

- Chat / Friends (Chat Window)
- Fire (Group Chat)
- Steam (File Transfer)
=======
- Add Participant
=======
- Alias
- Add Server
- Connected Server
- Ozone
=======
- Password 
- Public Data (Crypto Keys)
- About 

Exit & Screenlock remain at the burger three dots menu at right top.

Thanks.  
Lump-on

**Comment by textbrowser** [comment]
Like, I know who this is.

**Comment by textbrowser** [comment]
Will not be addressing a rewrite.

**Comment by textbrowser** [comment]
Completed.
