### ISSUE TITLE
Running on Linux

### ISSUE THREAD

**Issue by asakura42** [textbrowser/smoke#9]
Is it possible to run the app on Linux without a virtual machine? (I know it's not, but maybe you have some plans to expand device support because at first glance the app only lacks just cross-platform).

**Comment by asakura42** [comment]
I see you have similar project called 'Spot-On'. Is it relative to this project?

**Comment by textbrowser** [comment]
Smoke uses the Android framework.

No, not related. However, the programs can communicate with one another directly and indirectly.

**Comment by textbrowser** [comment]
There's Anbox. Smoke and SmokeStack function on it.

**Comment by textbrowser** [comment]
There's also https://www.android-x86.org/. So, if you have some legacy hardware, you can install Ax86 and use Smoke... like on a laptop.
